const TEENIEPING_DATA = [
  // ===== 로열 티니핑 1기 =====
  { name: "하츄핑", category: "로열 티니핑 1기", type: "royal", image: "assets/하츄핑.webp" },
  { name: "바로핑", category: "로열 티니핑 1기", type: "royal", image: "assets/바로핑.webp" },
  { name: "아자핑", category: "로열 티니핑 1기", type: "royal", image: "assets/아자핑.webp" },
  { name: "차차핑", category: "로열 티니핑 1기", type: "royal", image: "assets/차차핑.webp" },
  { name: "라라핑", category: "로열 티니핑 1기", type: "royal", image: "assets/라라핑.webp" },
  { name: "해핑", category: "로열 티니핑 1기", type: "royal", image: "assets/해핑.webp" },

  // ===== 로열 티니핑 2기 =====
  { name: "다이아 하츄핑", category: "로열 티니핑 2기", type: "royal", image: "assets/다이아 하츄핑.webp" },
  { name: "조아핑", category: "로열 티니핑 2기", type: "royal", image: "assets/조아핑.webp" },
  { name: "방글핑", category: "로열 티니핑 2기", type: "royal", image: "assets/방글핑.webp" },
  { name: "믿어핑", category: "로열 티니핑 2기", type: "royal", image: "assets/믿어핑.webp" },

  // ===== 로열 티니핑 3기 =====
  { name: "플로라 하츄핑", category: "로열 티니핑 3기", type: "royal", image: "assets/플로라 하츄핑.webp" },
  { name: "꾸래핑", category: "로열 티니핑 3기", type: "royal", image: "assets/꾸래핑.webp" },
  { name: "나나핑", category: "로열 티니핑 3기", type: "royal", image: "assets/나나핑.webp" },
  { name: "솔찌핑", category: "로열 티니핑 3기", type: "royal", image: "assets/솔찌핑.webp" },

  // ===== 로열 티니핑 4기 =====
  { name: "베리 하츄핑", category: "로열 티니핑 4기", type: "royal", image: "assets/베리 하츄핑.webp" },
  { name: "포실핑", category: "로열 티니핑 4기", type: "royal", image: "assets/포실핑.webp" },
  { name: "말랑핑", category: "로열 티니핑 4기", type: "royal", image: "assets/말랑핑.webp" },
  { name: "샤샤핑", category: "로열 티니핑 4기", type: "royal", image: "assets/샤샤핑.webp" },

  // ===== 로열 티니핑 5기 =====
  { name: "스타 하츄핑", category: "로열 티니핑 5기", type: "royal", image: "assets/스타 하츄핑.webp" },
  { name: "빛나핑", category: "로열 티니핑 5기", type: "royal", image: "assets/빛나핑.webp" },
  { name: "초롱핑", category: "로열 티니핑 5기", type: "royal", image: "assets/초롱핑.webp" },
  { name: "빤짝핑", category: "로열 티니핑 5기", type: "royal", image: "assets/빤짝핑.webp" },
  { name: "왕자핑", category: "로열 티니핑 5기", type: "royal", image: "assets/왕자핑.webp" },

  // ===== 로열 티니핑 6기 =====
  { name: "프린세스 하츄핑", category: "로열 티니핑 6기", type: "royal", image: "assets/프린세스 하츄핑.webp" },
  { name: "사뿐핑", category: "로열 티니핑 6기", type: "royal", image: "assets/사뿐핑.webp" },
  { name: "아름핑", category: "로열 티니핑 6기", type: "royal", image: "assets/아름핑.webp" },
  { name: "뽀니핑", category: "로열 티니핑 6기", type: "royal", image: "assets/뽀니핑.webp" },

  // ===== 레전드 티니핑 =====
  { name: "행운핑", category: "레전드 티니핑", type: "legend", image: "assets/행운핑.webp" },
  { name: "새콤핑", category: "레전드 티니핑", type: "legend", image: "assets/새콤핑.webp" },
  { name: "달콤핑", category: "레전드 티니핑", type: "legend", image: "assets/달콤핑.webp" },
  { name: "오로라핑", category: "레전드 티니핑", type: "legend", image: "assets/오로라핑.webp" },
  { name: "이클립스핑", category: "레전드 티니핑", type: "legend", image: "assets/이클립스핑.webp" },
  { name: "다이아나핑", category: "레전드 티니핑", type: "legend", image: "assets/다이아나핑.webp" },

  // ===== 1기 큐브 티니핑 =====
  { name: "키키핑", category: "큐브 티니핑 (1기)", type: "normal", image: "assets/키키핑.webp" },
  { name: "아잉핑", category: "큐브 티니핑 (1기)", type: "normal", image: "assets/아잉핑.webp" },
  { name: "부끄핑", category: "큐브 티니핑 (1기)", type: "normal", image: "assets/부끄핑.webp" },
  { name: "부투핑", category: "큐브 티니핑 (1기)", type: "normal", image: "assets/부투핑.webp" },
  { name: "깜빡핑", category: "큐브 티니핑 (1기)", type: "normal", image: "assets/깜빡핑.webp" },
  { name: "띠용핑", category: "큐브 티니핑 (1기)", type: "normal", image: "assets/띠용핑.webp" },
  { name: "주르핑", category: "큐브 티니핑 (1기)", type: "normal", image: "assets/주르핑.webp" },
  { name: "차나핑", category: "큐브 티니핑 (1기)", type: "normal", image: "assets/차나핑.webp" },
  { name: "따라핑", category: "큐브 티니핑 (1기)", type: "normal", image: "assets/따라핑.webp" },
  { name: "나르핑", category: "큐브 티니핑 (1기)", type: "normal", image: "assets/나르핑.webp" },
  { name: "무셔핑", category: "큐브 티니핑 (1기)", type: "normal", image: "assets/무셔핑.webp" },
  { name: "투투핑", category: "큐브 티니핑 (1기)", type: "normal", image: "assets/투투핑.webp" },
  { name: "차캐핑", category: "큐브 티니핑 (1기)", type: "normal", image: "assets/차캐핑.webp" },
  { name: "떠벌핑", category: "큐브 티니핑 (1기)", type: "normal", image: "assets/떠벌핑.webp" },
  { name: "다조핑", category: "큐브 티니핑 (1기)", type: "normal", image: "assets/다조핑.webp" },
  { name: "화나핑", category: "큐브 티니핑 (1기)", type: "normal", image: "assets/화나핑.webp" },
  { name: "시러핑", category: "큐브 티니핑 (1기)", type: "normal", image: "assets/시러핑.webp" },
  { name: "바네핑", category: "큐브 티니핑 (1기)", type: "normal", image: "assets/바네핑.webp" },
  { name: "덜덜핑", category: "큐브 티니핑 (1기)", type: "normal", image: "assets/덜덜핑.webp" },
  { name: "그림핑", category: "큐브 티니핑 (1기)", type: "normal", image: "assets/그림핑.webp" },
  { name: "무거핑", category: "큐브 티니핑 (1기)", type: "normal", image: "assets/무거핑.webp" },
  { name: "꺼꿀핑", category: "큐브 티니핑 (1기)", type: "normal", image: "assets/꺼꿀핑.webp" },
  { name: "씽씽핑", category: "큐브 티니핑 (1기)", type: "normal", image: "assets/씽씽핑.webp" },
  { name: "베베핑", category: "큐브 티니핑 (1기)", type: "normal", image: "assets/베베핑.webp" },
  { name: "코자핑", category: "큐브 티니핑 (1기)", type: "normal", image: "assets/코자핑.webp" },
  { name: "딱풀핑", category: "큐브 티니핑 (1기)", type: "normal", image: "assets/딱풀핑.webp" },
  { name: "모야핑", category: "큐브 티니핑 (1기)", type: "normal", image: "assets/모야핑.webp" },
  { name: "토이핑", category: "큐브 티니핑 (1기)", type: "normal", image: "assets/토이핑.webp" },
  { name: "또까핑", category: "큐브 티니핑 (1기)", type: "normal", image: "assets/또까핑.webp" },
  { name: "플라핑", category: "큐브 티니핑 (1기)", type: "normal", image: "assets/플라핑.webp" },
  { name: "노라핑 & 노리핑", category: "큐브 티니핑 (1기)", type: "normal", image: "assets/노라핑 & 노리핑.webp" },
  { name: "아휴핑", category: "큐브 티니핑 (1기)", type: "normal", image: "assets/아휴핑.webp" },
  { name: "똑똑핑", category: "큐브 티니핑 (1기)", type: "normal", image: "assets/똑똑핑.webp" },
  { name: "꽁꽁핑", category: "큐브 티니핑 (1기)", type: "normal", image: "assets/꽁꽁핑.webp" },
  { name: "찌릿핑", category: "큐브 티니핑 (1기)", type: "normal", image: "assets/찌릿핑.webp" },
  { name: "홀로핑", category: "큐브 티니핑 (1기)", type: "normal", image: "assets/홀로핑.webp" },
  { name: "앙대핑", category: "큐브 티니핑 (1기)", type: "normal", image: "assets/앙대핑.webp" },

  // ===== 2기 보석 티니핑 =====
  { name: "까르핑", category: "보석 티니핑 (2기)", type: "normal", image: "assets/까르핑.webp" },
  { name: "아야핑", category: "보석 티니핑 (2기)", type: "normal", image: "assets/아야핑.webp" },
  { name: "소원핑", category: "보석 티니핑 (2기)", type: "normal", image: "assets/소원핑.webp" },
  { name: "토닥핑", category: "보석 티니핑 (2기)", type: "normal", image: "assets/토닥핑.webp" },
  { name: "쪼꼼핑", category: "보석 티니핑 (2기)", type: "normal", image: "assets/쪼꼼핑.webp" },
  { name: "싹싹핑", category: "보석 티니핑 (2기)", type: "normal", image: "assets/싹싹핑.webp" },
  { name: "맛나핑", category: "보석 티니핑 (2기)", type: "normal", image: "assets/맛나핑.webp" },
  { name: "포근핑", category: "보석 티니핑 (2기)", type: "normal", image: "assets/포근핑.webp" },
  { name: "메모핑", category: "보석 티니핑 (2기)", type: "normal", image: "assets/메모핑.webp" },
  { name: "공쥬핑", category: "보석 티니핑 (2기)", type: "normal", image: "assets/공쥬핑.webp" },
  { name: "짝짝핑", category: "보석 티니핑 (2기)", type: "normal", image: "assets/짝짝핑.webp" },
  { name: "주네핑", category: "보석 티니핑 (2기)", type: "normal", image: "assets/주네핑.webp" },
  { name: "뚝딱핑", category: "보석 티니핑 (2기)", type: "normal", image: "assets/뚝딱핑.webp" },
  { name: "발레핑", category: "보석 티니핑 (2기)", type: "normal", image: "assets/발레핑.webp" },
  { name: "원더핑", category: "보석 티니핑 (2기)", type: "normal", image: "assets/원더핑.webp" },

  // ===== 3기 열쇠 티니핑 =====
  { name: "빨리핑", category: "열쇠 티니핑 (3기)", type: "normal", image: "assets/빨리핑.webp" },
  { name: "얌얌핑", category: "열쇠 티니핑 (3기)", type: "normal", image: "assets/얌얌핑.webp" },
  { name: "뜨거핑", category: "열쇠 티니핑 (3기)", type: "normal", image: "assets/뜨거핑.webp" },
  { name: "삐뽀핑", category: "열쇠 티니핑 (3기)", type: "normal", image: "assets/삐뽀핑.webp" },
  { name: "간호핑", category: "열쇠 티니핑 (3기)", type: "normal", image: "assets/간호핑.webp" },
  { name: "힘내핑", category: "열쇠 티니핑 (3기)", type: "normal", image: "assets/힘내핑.webp" },
  { name: "고쳐핑", category: "열쇠 티니핑 (3기)", type: "normal", image: "assets/고쳐핑.webp" },
  { name: "아라핑", category: "열쇠 티니핑 (3기)", type: "normal", image: "assets/아라핑.webp" },
  { name: "패션핑", category: "열쇠 티니핑 (3기)", type: "normal", image: "assets/패션핑.webp" },
  { name: "꼼딱핑", category: "열쇠 티니핑 (3기)", type: "normal", image: "assets/꼼딱핑.webp" },
  { name: "퐁당핑", category: "열쇠 티니핑 (3기)", type: "normal", image: "assets/퐁당핑.webp" },
  { name: "파티핑", category: "열쇠 티니핑 (3기)", type: "normal", image: "assets/파티핑.webp" },
  { name: "꾸며핑", category: "열쇠 티니핑 (3기)", type: "normal", image: "assets/꾸며핑.webp" },
  { name: "삐짐핑", category: "열쇠 티니핑 (3기)", type: "normal", image: "assets/삐짐핑.webp" },
  { name: "아아핑", category: "열쇠 티니핑 (3기)", type: "normal", image: "assets/아아핑.webp" },
  { name: "빙글핑", category: "열쇠 티니핑 (3기)", type: "normal", image: "assets/빙글핑.webp" },

  // ===== 4기 디저트 티니핑 =====
  { name: "캔디핑", category: "디저트 티니핑 (4기)", type: "normal", image: "assets/캔디핑.webp" },
  { name: "머랭핑", category: "디저트 티니핑 (4기)", type: "normal", image: "assets/머랭핑.webp" },
  { name: "샌드핑", category: "디저트 티니핑 (4기)", type: "normal", image: "assets/샌드핑.webp" },
  { name: "또너핑", category: "디저트 티니핑 (4기)", type: "normal", image: "assets/또너핑.webp" },
  { name: "와플핑", category: "디저트 티니핑 (4기)", type: "normal", image: "assets/와플핑.webp" },
  { name: "롤리핑", category: "디저트 티니핑 (4기)", type: "normal", image: "assets/롤리핑.webp" },
  { name: "마카핑", category: "디저트 티니핑 (4기)", type: "normal", image: "assets/마카핑.webp" },
  { name: "핫케핑", category: "디저트 티니핑 (4기)", type: "normal", image: "assets/핫케핑.webp" },
  { name: "커핑 & 머핑", category: "디저트 티니핑 (4기)", type: "normal", image: "assets/커핑 & 머핑.webp" },
  { name: "요거핑", category: "디저트 티니핑 (4기)", type: "normal", image: "assets/요거핑.webp" },
  { name: "눈꽃핑", category: "디저트 티니핑 (4기)", type: "normal", image: "assets/눈꽃핑.webp" },
  { name: "푸딩핑", category: "디저트 티니핑 (4기)", type: "normal", image: "assets/푸딩핑.webp" },
  { name: "멜로핑", category: "디저트 티니핑 (4기)", type: "normal", image: "assets/멜로핑.webp" },
  { name: "쪼꼬핑", category: "디저트 티니핑 (4기)", type: "normal", image: "assets/쪼꼬핑.webp" },
  { name: "뿌뿌핑", category: "디저트 티니핑 (4기)", type: "normal", image: "assets/뿌뿌핑.webp" },

  // ===== 5기 스타 티니핑 =====
  { name: "깡총핑", category: "스타 티니핑 (5기)", type: "normal", image: "assets/깡총핑.webp" },
  { name: "훌라핑", category: "스타 티니핑 (5기)", type: "normal", image: "assets/훌라핑.webp" },
  { name: "나눔핑", category: "스타 티니핑 (5기)", type: "normal", image: "assets/나눔핑.webp" },
  { name: "딩동핑", category: "스타 티니핑 (5기)", type: "normal", image: "assets/딩동핑.webp" },
  { name: "나그네핑", category: "스타 티니핑 (5기)", type: "normal", image: "assets/나그네핑.webp" },
  { name: "고고핑", category: "스타 티니핑 (5기)", type: "normal", image: "assets/고고핑.webp" },
  { name: "뿌쵸핑", category: "스타 티니핑 (5기)", type: "normal", image: "assets/뿌쵸핑.webp" },
  { name: "고마핑", category: "스타 티니핑 (5기)", type: "normal", image: "assets/고마핑.webp" },
  { name: "아롱핑", category: "스타 티니핑 (5기)", type: "normal", image: "assets/아롱핑.webp" },
  { name: "다롱핑", category: "스타 티니핑 (5기)", type: "normal", image: "assets/다롱핑.webp" },
  { name: "뽀송핑", category: "스타 티니핑 (5기)", type: "normal", image: "assets/뽀송핑.webp" },
  { name: "유리핑", category: "스타 티니핑 (5기)", type: "normal", image: "assets/유리핑.webp" },
  { name: "함께핑", category: "스타 티니핑 (5기)", type: "normal", image: "assets/함께핑.webp" },
  { name: "댄스핑", category: "스타 티니핑 (5기)", type: "normal", image: "assets/댄스핑.webp" },
  { name: "여우핑", category: "스타 티니핑 (5기)", type: "normal", image: "assets/여우핑.webp" },
  { name: "루루핑", category: "스타 티니핑 (5기)", type: "normal", image: "assets/루루핑.webp" },
  { name: "몰래핑", category: "스타 티니핑 (5기)", type: "normal", image: "assets/몰래핑.webp" },
  { name: "뽀뽀핑", category: "스타 티니핑 (5기)", type: "normal", image: "assets/뽀뽀핑.webp" },

  // ===== 6기 프린세스 티니핑 =====
  { name: "뽀득핑", category: "프린세스 티니핑 (6기)", type: "normal", image: "assets/뽀득핑.webp" },
  { name: "차밍핑", category: "프린세스 티니핑 (6기)", type: "normal", image: "assets/차밍핑.webp" },
  { name: "나비핑", category: "프린세스 티니핑 (6기)", type: "normal", image: "assets/나비핑.webp" },
  { name: "실크핑", category: "프린세스 티니핑 (6기)", type: "normal", image: "assets/실크핑.webp" },
  { name: "스노우핑", category: "프린세스 티니핑 (6기)", type: "normal", image: "assets/스노우핑.webp" },
  { name: "이슬핑", category: "프린세스 티니핑 (6기)", type: "normal", image: "assets/이슬핑.webp" },
  { name: "쿨쿨핑", category: "프린세스 티니핑 (6기)", type: "normal", image: "assets/쿨쿨핑.webp" },
  { name: "슈슈핑", category: "프린세스 티니핑 (6기)", type: "normal", image: "assets/슈슈핑.webp" },
  { name: "롱롱핑", category: "프린세스 티니핑 (6기)", type: "normal", image: "assets/롱롱핑.webp" },
  { name: "큐핑", category: "프린세스 티니핑 (6기)", type: "normal", image: "assets/큐핑.webp" },
  { name: "야옹핑", category: "프린세스 티니핑 (6기)", type: "normal", image: "assets/야옹핑.webp" },

  // ===== 6기 프린스 티니핑 =====
  { name: "샤를핑", category: "프린스 티니핑 (6기)", type: "normal", image: "assets/샤를핑.webp" },
  { name: "트롯핑", category: "프린스 티니핑 (6기)", type: "normal", image: "assets/트롯핑.webp" },
  { name: "깨굴핑", category: "프린스 티니핑 (6기)", type: "normal", image: "assets/깨굴핑.webp" },
  { name: "젠틀핑", category: "프린스 티니핑 (6기)", type: "normal", image: "assets/젠틀핑.webp" },

  // ===== 빌런 티니핑 =====
  { name: "트러핑", category: "빌런 티니핑", type: "normal", image: "assets/트러핑.webp" },
  { name: "다해핑", category: "빌런 티니핑", type: "normal", image: "assets/다해핑.webp" },
];
