const TEENIEPING_DATA = [
  // ===== 로열 티니핑 1기 =====
  { name: "하츄핑", season: "1기", collection: "로열 티니핑", tier: "royal", description: "사랑의 감정을 담당하는 최강의 로열 티니핑. 침착하고 이성적인 리더형 성격으로, 주인공 소미의 파트너이자 핑핑이들의 여왕이다.", image: "assets/하츄핑.webp" },
  { name: "바로핑", season: "1기", collection: "로열 티니핑", tier: "royal", description: "올바름의 감정을 담당하는 로열 티니핑. 존댓말을 사용하는 격식 있는 성격으로 로열핑 중 브레인 역할이며, 규칙을 어기면 잔소리를 아끼지 않는다.", image: "assets/바로핑.webp" },
  { name: "아자핑", season: "1기", collection: "로열 티니핑", tier: "royal", description: "용기의 감정을 담당하는 로열 티니핑. 생각보다 몸이 먼저 움직이는 열혈 다혈질 성격으로, 도망치거나 포기하는 것을 극도로 싫어한다.", image: "assets/아자핑.webp" },
  { name: "차차핑", season: "1기", collection: "로열 티니핑", tier: "royal", description: "희망의 감정을 담당하는 로열 티니핑. 어떤 힘든 상황에서도 좌절하지 않는 낙관적인 성격으로, 물뿌리개로 식물을 생생하게 만드는 마법을 보유한다.", image: "assets/차차핑.webp" },
  { name: "라라핑", season: "1기", collection: "로열 티니핑", tier: "royal", description: "즐거움의 감정을 담당하는 로열 티니핑. 수다쟁이에 쾌활한 분위기 메이커로, 노래를 좋아하지만 음치박치인 것이 특징이다.", image: "assets/라라핑.webp" },
  { name: "해핑", season: "1기", collection: "로열 티니핑", tier: "royal", description: "행복의 감정을 담당하는 로열 티니핑. 사소한 것에도 감탄하는 단순하고 낙천적인 성격으로, '~해피'라는 특유의 말버릇이 있다.", image: "assets/해핑.webp" },

  // ===== 로열 티니핑 2기 =====
  { name: "다이아 하츄핑", season: "2기", collection: "로열 티니핑", tier: "royal", description: "사랑을 담당하는 하츄핑의 2기 모습. 1기와 비교해 귀의 하트 장식이 보석 형태로 바뀌고 소품이 하프로 변경되었으며, '사랑의 선율' 마법으로 하트 모양 음표를 발사한다.", image: "assets/다이아 하츄핑.webp" },
  { name: "조아핑", season: "2기", collection: "로열 티니핑", tier: "royal", description: "친절의 감정을 담당하는 로열 티니핑. 다정하고 상냥하며 감수성이 풍부해 타인의 이야기를 깊이 공감하며, 브러쉬 소품으로 '친절의 쓰담쓰담' 마법을 사용해 동물들과 교감한다.", image: "assets/조아핑.webp" },
  { name: "방글핑", season: "2기", collection: "로열 티니핑", tier: "royal", description: "웃음의 감정을 담당하는 로열 티니핑. 발랄하고 충동적인 말괄량이로 언제나 방글방글 웃으며, 폭죽 소품으로 '웃음의 깜짝쇼' 마법을 발동해 랜덤 아이템을 소환한다.", image: "assets/방글핑.webp" },
  { name: "믿어핑", season: "2기", collection: "로열 티니핑", tier: "royal", description: "믿음의 감정을 담당하는 남성 로열 티니핑. 어수룩하고 순수하며 팔랑귀 성격으로 누구든 쉽게 믿고 행동하며, 마법 우산 소품으로 '믿음의 수호' 마법을 사용해 방어와 공격 모두 가능하다.", image: "assets/믿어핑.webp" },

  // ===== 로열 티니핑 3기 =====
  { name: "플로라 하츄핑", season: "3기", collection: "로열 티니핑", tier: "royal", description: "꽃을 모티브로 한 하츄핑의 3기 모습. 처음으로 옷을 입고 등장하며, '사랑의 향기' 마법으로 향수를 이용해 상대 공격을 막거나 향기에 취하게 만드는 능력을 지닌다.", image: "assets/플로라 하츄핑.webp" },
  { name: "꾸래핑", season: "3기", collection: "로열 티니핑", tier: "royal", description: "평화(온화함)의 감정을 담당하는 로열 티니핑. 온화하고 배려심이 많지만 화나면 거친 눈보라처럼 급변하는 이중성이 있으며, '그래'를 '꾸래'로 발음하는 특징이 있다.", image: "assets/꾸래핑.webp" },
  { name: "나나핑", season: "3기", collection: "로열 티니핑", tier: "royal", description: "열정의 감정을 담당하는 로열 티니핑. 언제나 파이팅이 넘치고 자신감이 강하지만, 열정에 비해 체력이 부족한 허당 면모도 있다.", image: "assets/나나핑.webp" },
  { name: "솔찌핑", season: "3기", collection: "로열 티니핑", tier: "royal", description: "솔직함의 감정을 담당하는 로열 티니핑. 감정과 본능에 솔직한 귀여운 투덜이로, 너무 솔직한 나머지 의도치 않게 상대를 불편하게 만들기도 한다.", image: "assets/솔찌핑.webp" },

  // ===== 로열 티니핑 4기 =====
  { name: "베리 하츄핑", season: "4기", collection: "로열 티니핑", tier: "royal", description: "딸기 케이크를 모티브로 한 하츄핑의 4기 모습. 최초로 키 아이템이 하트 모양을 벗어났으며, 핸드벨 소품으로 '사랑의 종소리' 마법을 사용해 딸기 타르트 모양 음표를 발산해 상대를 교란한다.", image: "assets/베리 하츄핑.webp" },
  { name: "포실핑", season: "4기", collection: "로열 티니핑", tier: "royal", description: "순수함의 감정을 담당하는 로열 티니핑. 순수하고 다정하며 의심할 줄 모르는 천연적 성격으로 먹보 속성이 강하며, 솜사탕 항아리와 스틱으로 '순수의 솜사탕' 마법을 사용해 솜사탕을 발사하거나 솜사탕 구름으로 이동한다.", image: "assets/포실핑.webp" },
  { name: "말랑핑", season: "4기", collection: "로열 티니핑", tier: "royal", description: "발랄하고 활발한 말괄량이 로열 티니핑. 깊게 생각하지 않고 행동하는 엉뚱한 성격이며, 탱탱볼로 젤리를 소환해 공격하거나 물체를 변형시키는 마법을 쓴다. 몸이 말랑해 늘어나거나 납작해질 수 있는 것이 특징이다.", image: "assets/말랑핑.webp" },
  { name: "샤샤핑", season: "4기", collection: "로열 티니핑", tier: "royal", description: "긍정의 감정을 담당하는 로열 티니핑. 낙천적이고 배려심 깊으며 포용력이 넓은 성격으로, 아이스크림 콘 모자로 아이스크림 요정들을 소환해 공격·지원·방어를 수행한다. 로열핑 최초로 모자를 마법 소품으로 사용하며 전용 아이스크림카를 보유한다.", image: "assets/샤샤핑.webp" },

  // ===== 로열 티니핑 5기 =====
  { name: "스타 하츄핑", season: "5기", collection: "로열 티니핑", tier: "royal", description: "귀 장식과 키 아이템이 모두 하트를 벗어난 하츄핑의 5기 모습. 글로우 퍼프 소품으로 별 모양 마법을 구사하며, 변신체 명칭이 이전과 달리 '프린세스 브라잇하트'로 완전히 새롭게 바뀌었다.", image: "assets/스타 하츄핑.webp" },
  { name: "빛나핑", season: "5기", collection: "로열 티니핑", tier: "royal", description: "치유의 감정을 담당하는 로열 티니핑. 플루트 연주로 상처받은 마음을 치유하며, 감수성이 풍부하지만 화가 나면 무섭게 돌변하는 이중성이 있다.", image: "assets/빛나핑.webp" },
  { name: "초롱핑", season: "5기", collection: "로열 티니핑", tier: "royal", description: "소망의 감정을 담당하는 로열 티니핑. 자기애가 강하고 당당한 성격으로 주목받기를 좋아하며, 다혈질이지만 의외로 겁이 많은 이중성이 있다.", image: "assets/초롱핑.webp" },
  { name: "빤짝핑", season: "5기", collection: "로열 티니핑", tier: "royal", description: "밝음(명석함)의 감정을 담당하는 로열 티니핑. 순진하고 아이 같아 보이지만 실은 똑똑한 괴짜로, 초승달 심볼과 솜인형 복화술 마법을 사용한다.", image: "assets/빤짝핑.webp" },
  { name: "왕자핑", season: "5기", collection: "로열 티니핑", tier: "royal", description: "우수(슬픔·근심)의 감정을 담당하는 유일한 남성 로열 티니핑. 책임감이 강하고 사랑하는 대상을 위해 수단과 방법을 가리지 않는 순애보 성격으로, 오로라핑과 커플이다.", image: "assets/왕자핑.webp" },

  // ===== 로열 티니핑 6기 =====
  { name: "프린세스 하츄핑", season: "6기", collection: "로열 티니핑", tier: "royal", description: "하츄핑의 6기 최강 형태. 요술봉을 소품으로 사용하며, 동료가 위기에 처할 때 흘리는 눈물이 부활의 마법 능력을 지닌다. 모든 에피소드에 출연하는 유일한 티니핑으로, 시즌을 거치며 성숙한 리더로 발전한다.", image: "assets/프린세스 하츄핑.webp" },
  { name: "사뿐핑", season: "6기", collection: "로열 티니핑", tier: "royal", description: "발레를 모티브로 한 로열 티니핑으로 '백조의 호수'에서 영감을 받았다. 과묵하고 외유내강의 성격으로, 요술봉으로 밟고 올라갈 수 있는 깃털을 소환하며 '프린세스 쁠리에'로 변신한다.", image: "assets/사뿐핑.webp" },
  { name: "아름핑", season: "6기", collection: "로열 티니핑", tier: "royal", description: "순수하고 감정이 풍부하며 남을 먼저 챙기는 따뜻한 성격의 로열 티니핑. 바느질이 특기이며 요술봉으로 원단으로 물체를 감싸는 마법을 사용한다. 복숭아를 닮은 귀여운 외모가 특징이다.", image: "assets/아름핑.webp" },
  { name: "뽀니핑", season: "6기", collection: "로열 티니핑", tier: "royal", description: "자신감의 감정을 담당하는 로열 티니핑. 쾌활하면서도 여린 마음의 외강내유형으로 맏언니 같은 리더십을 지니며, 기분 전환을 위해 헤어스타일을 자주 바꾸는 것으로 유명하다.", image: "assets/뽀니핑.webp" },

  // ===== 레전드 티니핑 =====
  { name: "행운핑", season: null, collection: "레전드 티니핑", tier: "legend", description: "행운의 감정을 담당하는 레전드 티니핑. 3기에 봉인이 해방된 뒤 처음엔 개그 캐릭터처럼 보이지만, 후반부에는 너그럽고 성숙한 대인배 면모를 드러낸다.", image: "assets/행운핑.webp" },
  { name: "새콤핑", season: null, collection: "레전드 티니핑", tier: "legend", description: "상큼함·새콤함의 감정을 담당하는 레전드 티니핑. 똑 부러지고 도도하며 자존심이 강한 성격으로, 녹색 별 모양 새콤 요술봉을 사용한다.", image: "assets/새콤핑.webp" },
  { name: "달콤핑", season: null, collection: "레전드 티니핑", tier: "legend", description: "달콤함의 감정을 담당하는 레전드 티니핑. 상냥하고 여유가 넘치는 성격으로 새콤핑의 단짝이며, 빨간 하트 모양 달콤 요술봉을 사용한다.", image: "assets/달콤핑.webp" },
  { name: "오로라핑", season: null, collection: "레전드 티니핑", tier: "legend", description: "약속의 감정을 담당하는 레전드 티니핑. 우주와 조화를 수호하며 기품 있는 성격으로, 왕자핑의 사랑으로 블랙홀에서 구원받은 왕자핑의 연인이다.", image: "assets/오로라핑.webp" },
  { name: "이클립스핑", season: null, collection: "레전드 티니핑", tier: "legend", description: "레전드 티니핑 최초의 빌런. 거울의 성의 주인으로, 외로움과 소외감으로 타락했다. 다이아나핑의 여동생이며, 분위기를 잡다 실수하는 의외의 허당 면모도 있다.", image: "assets/이클립스핑.webp" },
  { name: "다이아나핑", season: null, collection: "레전드 티니핑", tier: "legend", description: "영광의 감정을 담당하는 레전드 티니핑. 프린세스&프린스 티니핑 국가연합의 의장으로, 이클립스핑(여동생)에 의해 거울 안에 봉인된다.", image: "assets/다이아나핑.webp" },

  // ===== 큐브 티니핑 1기 =====
  { name: "키키핑", season: "1기", collection: "큐브 티니핑", tier: "normal", description: "장난과 개구짐의 감정을 담당하는 큐브 티니핑. 산만하고 요란스러우며, 막대사탕 마법으로 상대를 장난꾸러기로 만드는 능력이 있다.", image: "assets/키키핑.webp" },
  { name: "아잉핑", season: "1기", collection: "큐브 티니핑", tier: "normal", description: "애교와 사랑의 감정을 담당하는 큐브 티니핑. 엉뚱하고 발랄한 애교쟁이로, 리본봉 마법으로 상대를 심각한 애교쟁이로 만드는 능력이 있다.", image: "assets/아잉핑.webp" },
  { name: "부끄핑", season: "1기", collection: "큐브 티니핑", tier: "normal", description: "부끄러움의 감정을 담당하는 큐브 티니핑. 주목받는 것을 싫어하는 수줍음쟁이로, 당근쿠션 마법으로 상대를 극심한 부끄럼쟁이로 만드는 능력이 있다.", image: "assets/부끄핑.webp" },
  { name: "부투핑", season: "1기", collection: "큐브 티니핑", tier: "normal", description: "승부욕의 감정을 담당하는 큐브 티니핑. 승패를 가려야만 직성이 풀리는 열혈한 성격으로, 스포츠 심판을 모티브로 한다.", image: "assets/부투핑.webp" },
  { name: "깜빡핑", season: "1기", collection: "큐브 티니핑", tier: "normal", description: "망각의 감정을 담당하는 큐브 티니핑. 건망증이 심한 덜렁이로, 지우개 소품으로 상대가 잠시 무언가를 잊게 만드는 마법을 쓴다.", image: "assets/깜빡핑.webp" },
  { name: "띠용핑", season: "1기", collection: "큐브 티니핑", tier: "normal", description: "상상력과 엉뚱함의 감정을 담당하는 큐브 티니핑. 재미있는 상상을 좋아하는 엉뚱한 성격으로, 대상에게 원하는 것이 보이는 환각을 만드는 마법을 쓴다.", image: "assets/띠용핑.webp" },
  { name: "주르핑", season: "1기", collection: "큐브 티니핑", tier: "normal", description: "슬픔과 울고 싶은 마음을 담당하는 큐브 티니핑. 사람들을 울게 해 그 눈물을 맛있는 눈물사탕으로 변환하는 마법을 쓴다.", image: "assets/주르핑.webp" },
  { name: "차나핑", season: "1기", collection: "큐브 티니핑", tier: "normal", description: "귀찮음의 감정을 담당하는 큐브 티니핑. 모든 것을 귀찮아하는 극도의 게으름뱅이로, 상대의 의욕을 상실시키고 행동을 느리게 만드는 마법을 쓴다.", image: "assets/차나핑.webp" },
  { name: "따라핑", season: "1기", collection: "큐브 티니핑", tier: "normal", description: "모방의 감정을 담당하는 큐브 티니핑. 다른 존재를 흉내 내며 놀리는 것을 즐기는 성격으로, 대상이 원하는 누군가의 행동을 따라하게 만드는 마법을 쓴다.", image: "assets/따라핑.webp" },
  { name: "나르핑", season: "1기", collection: "큐브 티니핑", tier: "normal", description: "나르시시즘(자기애)의 감정을 담당하는 큐브 티니핑. 외모에 집착하는 자기애 강한 성격으로, 손거울로 대상을 자기애 중심적으로 만드는 마법을 쓴다.", image: "assets/나르핑.webp" },
  { name: "무셔핑", season: "1기", collection: "큐브 티니핑", tier: "normal", description: "두려움의 감정을 담당하는 큐브 티니핑. 자신을 용감하다 여기지만 실은 엄청난 겁쟁이로, 손전등으로 대상이 두려워하는 것을 보여주는 마법을 쓴다.", image: "assets/무셔핑.webp" },
  { name: "투투핑", season: "1기", collection: "큐브 티니핑", tier: "normal", description: "질투의 감정을 담당하는 큐브 티니핑. 로미 공주를 유독 따르는 자존심 강한 성격으로, 눈빛 마법으로 상대의 질투심을 자극하는 능력이 있다.", image: "assets/투투핑.webp" },
  { name: "차캐핑", season: "1기", collection: "큐브 티니핑", tier: "normal", description: "배려심의 감정을 담당하는 큐브 티니핑. 도움이 필요한 사람을 외면하지 못하는 착한 성격으로, 착한 일을 한 아이의 손에 도장을 찍어 하루를 행운으로 만들어주는 능력이 있다.", image: "assets/차캐핑.webp" },
  { name: "떠벌핑", season: "1기", collection: "큐브 티니핑", tier: "normal", description: "수다와 경박함의 감정을 담당하는 큐브 티니핑. 남의 비밀을 쉽게 퍼뜨리는 성격으로, 확성기 마법으로 상대가 속으로 생각하는 것을 강제로 발설하게 한다.", image: "assets/떠벌핑.webp" },
  { name: "다조핑", season: "1기", collection: "큐브 티니핑", tier: "normal", description: "욕심의 감정을 담당하는 큐브 티니핑. 먹을 것과 반짝이는 물건을 탐내며 절대 양보하지 않는 성격으로, 바구니 마법으로 원하는 것을 어디서든 가져오는 능력이 있다.", image: "assets/다조핑.webp" },
  { name: "화나핑", season: "1기", collection: "큐브 티니핑", tier: "normal", description: "분노의 감정을 담당하는 큐브 티니핑. 쉽게 화를 내지만 금방 풀리는 다혈질 성격이다.", image: "assets/화나핑.webp" },
  { name: "시러핑", season: "1기", collection: "큐브 티니핑", tier: "normal", description: "거부감과 거절의 감정을 담당하는 큐브 티니핑. 모든 것을 싫다며 투덜거리는 청개구리 같은 성격으로, 거부 마법으로 상대가 모든 것을 거절하게 만드는 능력이 있다.", image: "assets/시러핑.webp" },
  { name: "바네핑", season: "1기", collection: "큐브 티니핑", tier: "normal", description: "이끌림의 감정을 담당하는 큐브 티니핑. 마법의 활과 화살로 맞은 상대가 처음 보는 것에 반하게 만드는 능력이 있다.", image: "assets/바네핑.webp" },
  { name: "덜덜핑", season: "1기", collection: "큐브 티니핑", tier: "normal", description: "차가움을 사랑하는 큐브 티니핑. 막대 아이스크림을 소품으로 사용하며, 사물을 얼리고 대상이 추위를 느끼게 하는 마법을 쓴다. 꽁꽁핑의 단짝이다.", image: "assets/덜덜핑.webp" },
  { name: "그림핑", season: "1기", collection: "큐브 티니핑", tier: "normal", description: "예술감의 감정을 담당하는 큐브 티니핑. 자신의 예술에 강한 자부심을 가진 나르시시스트 기질의 화가로, 그림으로 실제 물체를 실체화하는 능력이 있다.", image: "assets/그림핑.webp" },
  { name: "무거핑", season: "1기", collection: "큐브 티니핑", tier: "normal", description: "무거움의 감정을 담당하는 큐브 티니핑. 운동을 좋아하며 근육을 자랑하는 자신감 넘치는 성격으로, 주변 물체를 무겁게 만드는 능력이 있다.", image: "assets/무거핑.webp" },
  { name: "꺼꿀핑", season: "1기", collection: "큐브 티니핑", tier: "normal", description: "반대/거꾸로의 감정을 담당하는 큐브 티니핑. 뭐든지 반대로 뒤집는 것을 즐기는 엉뚱한 성격으로, 대상을 반대로 움직이게 하는 마법을 사용한다.", image: "assets/꺼꿀핑.webp" },
  { name: "씽씽핑", season: "1기", collection: "큐브 티니핑", tier: "normal", description: "속도감의 감정을 담당하는 큐브 티니핑. 빠른 것에 집착하는 자만심 강한 성격으로, 대상의 움직임 속도를 자유자재로 제어하는 능력을 지닌다.", image: "assets/씽씽핑.webp" },
  { name: "베베핑", season: "1기", collection: "큐브 티니핑", tier: "normal", description: "동심의 감정을 담당하는 큐브 티니핑. 아기처럼 제멋대로이지만 명랑하고 순수한 성향으로, 마법으로 사람들을 아기로 변신시키는 능력이 있다.", image: "assets/베베핑.webp" },
  { name: "코자핑", season: "1기", collection: "큐브 티니핑", tier: "normal", description: "졸음의 감정을 담당하는 큐브 티니핑. 타인의 꿈을 들여다보기 좋아하는 호기심 많은 성격으로, 대상을 잠들게 해 꿈젤리를 만드는 능력이 있다.", image: "assets/코자핑.webp" },
  { name: "딱풀핑", season: "1기", collection: "큐브 티니핑", tier: "normal", description: "유대감의 감정을 담당하는 큐브 티니핑. 발랄하고 쾌활하며 싸우는 것을 극도로 싫어해 사이좋게 지내길 원하고, 대상들을 붙여버리는 마법을 사용한다.", image: "assets/딱풀핑.webp" },
  { name: "모야핑", season: "1기", collection: "큐브 티니핑", tier: "normal", description: "호기심의 감정을 담당하는 큐브 티니핑. '모야모야?' 하며 모든 것이 궁금한 성격으로, 돋보기를 소품으로 사용해 물체를 거대하게 만드는 마법을 쓴다.", image: "assets/모야핑.webp" },
  { name: "토이핑", season: "1기", collection: "큐브 티니핑", tier: "normal", description: "애착의 감정을 담당하는 큐브 티니핑. 지루한 것을 싫어하고 재미있는 것을 좋아하는 개구쟁이로, 모든 사물을 장난감으로 변환하는 능력이 있다.", image: "assets/토이핑.webp" },
  { name: "또까핑", season: "1기", collection: "큐브 티니핑", tier: "normal", description: "동경심의 감정을 담당하는 큐브 티니핑. 발랄하지만 허당 기질이 있으며, 가면을 이용해 다른 사람의 모습을 3분간 복사하는 변신 능력을 지닌다.", image: "assets/또까핑.webp" },
  { name: "플라핑", season: "1기", collection: "큐브 티니핑", tier: "normal", description: "꽃을 사랑하는 마음을 담당하는 큐브 티니핑. 나긋나긋하고 우아한 성격으로 꽃에 강한 열정을 가지며, 대상을 꽃으로 변환하는 마법을 쓴다.", image: "assets/플라핑.webp" },
  { name: "노라핑 & 노리핑", season: "1기", collection: "큐브 티니핑", tier: "normal", description: "형 노라핑은 놀고 싶은 마음, 동생 노리핑은 천진무구함의 감정을 담당한다. 형은 장난기 많고 활발하며, 동생은 호기심 왕성한 아기 티니핑이다.", image: "assets/노라핑 & 노리핑.webp" },
  { name: "아휴핑", season: "1기", collection: "큐브 티니핑", tier: "normal", description: "걱정과 부정적 예감의 감정을 담당하는 큐브 티니핑. 극도로 소심하고 의기소침한 성격이며, 나팔을 불면 듣는 사람을 불행하게 만드는 마법을 사용한다.", image: "assets/아휴핑.webp" },
  { name: "똑똑핑", season: "1기", collection: "큐브 티니핑", tier: "normal", description: "학구열의 감정을 담당하는 큐브 티니핑. 무뚝뚝한 모범생으로 조용한 환경을 극도로 선호하며, 대상을 일시정지시켜 구구단을 외우게 만드는 마법을 사용한다.", image: "assets/똑똑핑.webp" },
  { name: "꽁꽁핑", season: "1기", collection: "큐브 티니핑", tier: "normal", description: "냉랭함의 감정을 담당하는 큐브 티니핑. 겉으로는 차갑지만 우정을 아주 중요하게 여기는 츤데레 성격으로, 대상을 얼리는 아이스 마법을 사용한다.", image: "assets/꽁꽁핑.webp" },
  { name: "찌릿핑", season: "1기", collection: "큐브 티니핑", tier: "normal", description: "짜릿함과 스릴의 감정을 담당하는 큐브 티니핑. 스릴과 짜릿한 상황을 즐기는 무모하고 장난기 많은 성격으로, 전기를 발생시켜 상대를 감전시키는 능력이 있다.", image: "assets/찌릿핑.webp" },
  { name: "홀로핑", season: "1기", collection: "큐브 티니핑", tier: "normal", description: "고독함의 감정을 담당하는 큐브 티니핑. 혼자 지내는 것을 좋아하고 떠들썩한 분위기를 싫어하는 성격으로, 낚싯대로 방어막을 형성하는 능력이 있다.", image: "assets/홀로핑.webp" },
  { name: "앙대핑", season: "1기", collection: "큐브 티니핑", tier: "normal", description: "이기심의 감정을 담당하는 큐브 티니핑. 제멋대로이며 질서를 싫어하고 여러 감정을 뒤섞어 싸움을 부추기는 1기 최종 빌런이다.", image: "assets/앙대핑.webp" },

  // ===== 보석 티니핑 2기 =====
  { name: "까르핑", season: "2기", collection: "보석 티니핑", tier: "normal", description: "짓궂음과 장난의 감정을 담당하는 보석 티니핑. 간지럼 부채로 사람들을 자지러지게 웃게 만드는 익살맞고 발랄한 성격이다.", image: "assets/까르핑.webp" },
  { name: "아야핑", season: "2기", collection: "보석 티니핑", tier: "normal", description: "엄살의 감정을 담당하는 보석 티니핑. 작은 일도 크게 과장하는 극도로 예민하고 칭얼거리는 어리광쟁이로, 반창고를 소품으로 사용한다.", image: "assets/아야핑.webp" },
  { name: "소원핑", season: "2기", collection: "보석 티니핑", tier: "normal", description: "소원의 감정을 담당하는 보석 티니핑. 순수하고 순진한 성격이지만 어딘가 허술한 엉뚱한 요정으로, 세 가지 소원을 예상 밖의 방식으로 이루어주는 능력이 있다.", image: "assets/소원핑.webp" },
  { name: "토닥핑", season: "2기", collection: "보석 티니핑", tier: "normal", description: "위로의 감정을 담당하는 보석 티니핑. 이해심 깊고 따뜻한 마음씨로 존댓말을 사용하는 성숙한 성격이며, 애착담요로 실의에 빠진 이를 위로하는 능력이 있다.", image: "assets/토닥핑.webp" },
  { name: "쪼꼼핑", season: "2기", collection: "보석 티니핑", tier: "normal", description: "소심함의 감정을 담당하는 보석 티니핑. 내성적이고 겁이 많아 남의 눈에 띄지 않으려 어딘가 숨어버리는 성격으로, 아코디언으로 대상의 크기를 줄이는 마법을 쓴다.", image: "assets/쪼꼼핑.webp" },
  { name: "싹싹핑", season: "2기", collection: "보석 티니핑", tier: "normal", description: "깔끔함의 감정을 담당하는 보석 티니핑. 더러운 것을 절대 참지 못하는 결벽증적 성격으로, 마법의 빗자루로 물건들을 자동으로 정리정돈하는 능력이 있다.", image: "assets/싹싹핑.webp" },
  { name: "맛나핑", season: "2기", collection: "보석 티니핑", tier: "normal", description: "미각의 감정을 담당하는 보석 티니핑. 충청도 사투리를 사용하는 능청스럽고 넉살 좋은 요리사 티니핑으로, 마법의 국자로 요리와 관련된 능력을 발휘한다.", image: "assets/맛나핑.webp" },
  { name: "포근핑", season: "2기", collection: "보석 티니핑", tier: "normal", description: "포근함의 감정을 담당하는 보석 티니핑. 뜨개질을 너무나도 좋아하는 온순한 성격으로, 마법의 뜨개바늘로 물체를 양털 뜨개 소품으로 바꾸는 능력이 있다.", image: "assets/포근핑.webp" },
  { name: "메모핑", season: "2기", collection: "보석 티니핑", tier: "normal", description: "꼼꼼함의 감정을 담당하는 보석 티니핑. 겉으로는 장난꾸러기처럼 보이지만 사실은 친구들의 관심을 받고 싶은 외로운 요정으로, 다이어리에 메모한 내용을 현실로 만드는 능력이 있다.", image: "assets/메모핑.webp" },
  { name: "공쥬핑", season: "2기", collection: "보석 티니핑", tier: "normal", description: "우아함의 감정을 담당하는 보석 티니핑. 자신을 이모션 왕국의 공주라 여기는 제멋대로이면서도 순진한 성격으로, 마법봉으로 다른 이를 원하는 직위로 만드는 능력이 있다.", image: "assets/공쥬핑.webp" },
  { name: "짝짝핑", season: "2기", collection: "보석 티니핑", tier: "normal", description: "외로움의 감정을 담당하는 보석 티니핑. 외로움을 잘 타서 혼자 1인 2역을 하는 수다쟁이로, 마법의 캐스터네츠로 대상을 좌우반전된 복제본으로 만드는 능력이 있다.", image: "assets/짝짝핑.webp" },
  { name: "주네핑", season: "2기", collection: "보석 티니핑", tier: "normal", description: "나눔과 기부의 감정을 담당하는 보석 티니핑. 발랄하고 활기차며 아이들에게 선물을 나눠주는 것을 좋아하는 산타클로스 모티브의 요정이다.", image: "assets/주네핑.webp" },
  { name: "뚝딱핑", season: "2기", collection: "보석 티니핑", tier: "normal", description: "창의력의 감정을 담당하는 보석 티니핑. 감수성이 풍부한 조각가 요정으로, 마법의 망치로 조각상을 만들어 살아 움직이게 하는 능력이 있다.", image: "assets/뚝딱핑.webp" },
  { name: "발레핑", season: "2기", collection: "보석 티니핑", tier: "normal", description: "유연함의 감정을 담당하는 보석 티니핑. 발레를 사랑하며 고집스럽지만 진취적인 성격으로, 처음엔 엄격하지만 타인의 노력을 인정할 줄 아는 성숙함을 지닌다.", image: "assets/발레핑.webp" },
  { name: "원더핑", season: "2기", collection: "보석 티니핑", tier: "normal", description: "영웅심의 감정을 담당하는 보석 티니핑. 불의를 보면 참지 못하는 정의감 강하고 용기와 자신감이 넘치는 히어로 지망생이다.", image: "assets/원더핑.webp" },

  // ===== 열쇠 티니핑 3기 =====
  { name: "빨리핑", season: "3기", collection: "열쇠 티니핑", tier: "normal", description: "조급함의 감정을 담당하는 열쇠 티니핑. 뭐든 빨리빨리 서두르고 느긋함을 싫어하는 성격으로, 마법의 회중시계로 대상을 조급하게 만드는 능력이 있다.", image: "assets/빨리핑.webp" },
  { name: "얌얌핑", season: "3기", collection: "열쇠 티니핑", tier: "normal", description: "배고픔의 감정을 담당하는 열쇠 티니핑. 식탐이 많고 모든 사람이 맛있게 먹으며 행복하기를 바라는 성격으로, 마법의 포크로 상대의 식욕을 증폭시키는 능력이 있다.", image: "assets/얌얌핑.webp" },
  { name: "뜨거핑", season: "3기", collection: "열쇠 티니핑", tier: "normal", description: "철저함의 감정을 담당하는 열쇠 티니핑. '불타는 건 모두 꺼야 해'라는 신념의 소방관 모티브 요정으로, 마법의 소화기로 모든 불을 진화하는 능력이 있다.", image: "assets/뜨거핑.webp" },
  { name: "삐뽀핑", season: "3기", collection: "열쇠 티니핑", tier: "normal", description: "돌봄의 감정을 담당하는 열쇠 티니핑. 엉뚱하지만 환자를 진심으로 생각하는 의사 모티브 요정으로, 전문성은 부족해도 환자를 돌보려는 헌신적인 마음만큼은 진정한 의료인이다.", image: "assets/삐뽀핑.webp" },
  { name: "간호핑", season: "3기", collection: "열쇠 티니핑", tier: "normal", description: "돌봄의 감정을 담당하는 열쇠 티니핑. 삐뽀핑의 조수 역할을 하는 4명의 간호사 티니핑으로, 삐뽀핑을 '선생님'이라 부르며 충성스럽게 따른다.", image: "assets/간호핑.webp" },
  { name: "힘내핑", season: "3기", collection: "열쇠 티니핑", tier: "normal", description: "격려와 응원의 감정을 담당하는 열쇠 티니핑. 인품이 좋고 포기를 싫어하는 성격이지만 어리숙하고 엉뚱한 탓에 응원이 오히려 역효과를 내기도 하는 치어리더 요정이다.", image: "assets/힘내핑.webp" },
  { name: "고쳐핑", season: "3기", collection: "열쇠 티니핑", tier: "normal", description: "이타심의 감정을 담당하는 열쇠 티니핑. 타인을 돕고자 하는 강한 마음을 가진 수리공 요정으로, 고장 난 물건을 고쳐주지만 초기에는 엉뚱하게 고쳐지는 경우가 많았다.", image: "assets/고쳐핑.webp" },
  { name: "아라핑", season: "3기", collection: "열쇠 티니핑", tier: "normal", description: "탐구심과 발명심의 감정을 담당하는 열쇠 티니핑. '역시 난 천재야'라는 자신감 강한 성격의 발명가 요정으로, 다양한 물약을 제조하는 능력을 지닌다.", image: "assets/아라핑.webp" },
  { name: "패션핑", season: "3기", collection: "열쇠 티니핑", tier: "normal", description: "독창성의 감정을 담당하는 열쇠 티니핑. 천재라는 자부심이 강한 패션 디자이너 요정으로, 마법으로 대상을 마네킹으로 만들어 옷을 입히는 능력이 있다.", image: "assets/패션핑.webp" },
  { name: "꼼딱핑", season: "3기", collection: "열쇠 티니핑", tier: "normal", description: "정의감의 감정을 담당하는 열쇠 티니핑. 경찰 옷을 입고 경찰 바이크를 타며, 마법의 호루라기로 대상의 두 손을 번쩍 들게 만드는 능력이 있다. 다만 성급한 탓에 억측으로 누명을 잘 씌운다.", image: "assets/꼼딱핑.webp" },
  { name: "퐁당핑", season: "3기", collection: "열쇠 티니핑", tier: "normal", description: "자유로움의 감정을 담당하는 열쇠 티니핑. 인어 모습을 한 티니핑으로 억압받는 것을 싫어하며 친절하고 따뜻한 성격이다. 열쇠 티니핑 인기 1위를 기록했다.", image: "assets/퐁당핑.webp" },
  { name: "파티핑", season: "3기", collection: "열쇠 티니핑", tier: "normal", description: "유희의 감정을 담당하는 열쇠 티니핑. 파티를 극도로 좋아하는 화려함 추구형 성격으로, 마법의 코끼리피리로 대상을 파티 환각에 빠뜨리는 능력이 있다.", image: "assets/파티핑.webp" },
  { name: "꾸며핑", season: "3기", collection: "열쇠 티니핑", tier: "normal", description: "가꿈의 감정을 담당하는 열쇠 티니핑. 예쁜 머리를 꾸미길 좋아하는 미용사 요정으로, 겉보기엔 남의 머리를 망치는 것 같지만 사실 타인의 성장을 돕는 착한 마음씨를 가졌다.", image: "assets/꾸며핑.webp" },
  { name: "삐짐핑", season: "3기", collection: "열쇠 티니핑", tier: "normal", description: "토라짐의 감정을 담당하는 열쇠 티니핑. 관심에 굶주린 응석받이 성격으로, 마법의 막대사탕으로 대상을 토라지게 만들거나 친구들 사이에 갈등을 일으키는 능력이 있다.", image: "assets/삐짐핑.webp" },
  { name: "아아핑", season: "3기", collection: "열쇠 티니핑", tier: "normal", description: "리듬감의 감정을 담당하는 열쇠 티니핑. 노래와 바이올린 연주를 사랑하는 따뜻한 성격의 음악가 요정으로, 절대음감과 음파 공격 등 강력한 전투 능력도 지닌다.", image: "assets/아아핑.webp" },
  { name: "빙글핑", season: "3기", collection: "열쇠 티니핑", tier: "normal", description: "표현력의 감정을 담당하는 열쇠 티니핑. 피겨 스케이팅에 진지한 완벽주의 성격의 요정으로, 팽이를 사용해 대상이 피겨 스케이팅 동작을 따라하게 만드는 능력이 있다.", image: "assets/빙글핑.webp" },

  // ===== 디저트 티니핑 4기 =====
  { name: "캔디핑", season: "4기", collection: "디저트 티니핑", tier: "normal", description: "솔깃함(달콤한 말)의 감정을 담당하는 디저트 티니핑. 마법으로 상대에게 듣기 좋은 말을 하게 만들며, 싸움과 상처 주는 말을 싫어하는 긍정적인 성격이다.", image: "assets/캔디핑.webp" },
  { name: "머랭핑", season: "4기", collection: "디저트 티니핑", tier: "normal", description: "장식의 감정을 담당하는 디저트 티니핑. 화려하고 예쁜 것을 좋아하며 거품기로 모든 것을 예쁘게 꾸미는 고집 있는 순수한 성격이다.", image: "assets/머랭핑.webp" },
  { name: "샌드핑", season: "4기", collection: "디저트 티니핑", tier: "normal", description: "친밀함의 감정을 담당하는 디저트 티니핑. '빈 곳이 있으면 모조리 채워줄거야'라는 신념으로 마법의 스패츌러로 빈 곳을 크림으로 채우는 따뜻한 성격이다.", image: "assets/샌드핑.webp" },
  { name: "또너핑", season: "4기", collection: "디저트 티니핑", tier: "normal", description: "상쾌함의 감정을 담당하는 디저트 티니핑. 어리고 장난스럽지만 어린애 취급을 싫어하며, 로열핑을 꿈꾸는 성장형 캐릭터이다.", image: "assets/또너핑.webp" },
  { name: "와플핑", season: "4기", collection: "디저트 티니핑", tier: "normal", description: "납작함의 감정을 담당하는 디저트 티니핑. 참을성이 없고 뭐든 빨리 하려는 충동적인 개구쟁이로, 심벌즈로 물체를 납작하게 만드는 마법을 쓴다.", image: "assets/와플핑.webp" },
  { name: "롤리핑", season: "4기", collection: "디저트 티니핑", tier: "normal", description: "회전의 감정을 담당하는 디저트 티니핑. 빙빙 도는 것을 좋아하는 순수하고 천진난만한 성격으로, 바람개비로 대상을 어지럽게 만드는 마법을 쓴다.", image: "assets/롤리핑.webp" },
  { name: "마카핑", season: "4기", collection: "디저트 티니핑", tier: "normal", description: "색감의 감정을 담당하는 디저트 티니핑. 알록달록한 것을 좋아하고 생각 없이 행동하는 단순하고 해맑은 성격으로, 마법의 짤주머니로 색을 자유롭게 바꾼다.", image: "assets/마카핑.webp" },
  { name: "핫케핑", season: "4기", collection: "디저트 티니핑", tier: "normal", description: "성취감의 감정을 담당하는 디저트 티니핑. 무언가를 쌓을 때 큰 만족감을 느끼며, 마법 프라이팬으로 물건을 차곡차곡 쌓는 푸근하고 정직한 성격이다.", image: "assets/핫케핑.webp" },
  { name: "커핑 & 머핑", season: "4기", collection: "디저트 티니핑", tier: "normal", description: "우애의 감정을 담당하는 쌍둥이 디저트 티니핑. 항상 함께 붙어 다니는 장난꾸러기로, 쪽쪽이를 빼앗기면 몸이 거대해질 만큼 격하게 반응한다.", image: "assets/커핑 & 머핑.webp" },
  { name: "요거핑", season: "4기", collection: "디저트 티니핑", tier: "normal", description: "편안함의 감정을 담당하는 디저트 티니핑. 배려심 깊은 성격으로 요들 노래와 마법 숟가락으로 대상을 깊은 잠에 빠지게 하며, 요거트양 2마리와 항상 함께한다.", image: "assets/요거핑.webp" },
  { name: "눈꽃핑", season: "4기", collection: "디저트 티니핑", tier: "normal", description: "천진난만함의 감정을 담당하는 디저트 티니핑. 강한 마력을 제어하지 못해 외톨이였지만, 따뜻한 마음씨로 자신을 괴롭힌 뿌뿌핑에게도 위로를 건네는 대인배이다.", image: "assets/눈꽃핑.webp" },
  { name: "푸딩핑", season: "4기", collection: "디저트 티니핑", tier: "normal", description: "유약함의 감정을 담당하는 디저트 티니핑. 상처받으면 움츠러들지만 신나는 음악이 흐르면 자기도 모르게 춤을 추고 주변을 모두 춤추게 만드는 흥 넘치는 성격이다.", image: "assets/푸딩핑.webp" },
  { name: "멜로핑", season: "4기", collection: "디저트 티니핑", tier: "normal", description: "폭신함의 감정을 담당하는 디저트 티니핑. 상냥하고 친절하지만 눈치가 조금 없으며, 마시멜롱 인형을 활용해 주변 물체를 폭신하게 만드는 순진한 성격이다.", image: "assets/멜로핑.webp" },
  { name: "쪼꼬핑", season: "4기", collection: "디저트 티니핑", tier: "normal", description: "변화(화합)의 감정을 담당하는 디저트 티니핑. 다정하고 활발하며 다투는 친구들에게 초코 모자를 씌워 사이좋게 만들어주는 사랑 넘치는 성격이다.", image: "assets/쪼꼬핑.webp" },
  { name: "뿌뿌핑", season: "4기", collection: "디저트 티니핑", tier: "normal", description: "흥미의 감정을 담당하는 디저트 티니핑. 재치 있고 똑똑하지만 소외감으로 인해 장난과 골탕 먹이기를 일삼는 트러블 메이커이다.", image: "assets/뿌뿌핑.webp" },

  // ===== 스타 티니핑 5기 =====
  { name: "깡총핑", season: "5기", collection: "스타 티니핑", tier: "normal", description: "극복의 감정을 담당하는 스타 티니핑. 좌절해도 금방 일어나는 낙천적인 성격으로, 줄넘기 마법으로 주변을 토끼처럼 뛰게 만드는 포기를 모르는 노력파이다.", image: "assets/깡총핑.webp" },
  { name: "훌라핑", season: "5기", collection: "스타 티니핑", tier: "normal", description: "활동심의 감정을 담당하는 스타 티니핑. 활발하고 긍정적인 말괄량이로, 마법의 훌라후프로 대상을 즐겁게 훌라후프 돌리게 만드는 뛰어난 전투력을 보유한다.", image: "assets/훌라핑.webp" },
  { name: "나눔핑", season: "5기", collection: "스타 티니핑", tier: "normal", description: "나눔의 감정을 담당하는 스타 티니핑. 다정하고 따뜻하며 배려심이 많아 빛을 나눠주는 마법으로 주변을 밝히고, 필요하다면 자신을 희생하는 이타적인 성격이다.", image: "assets/나눔핑.webp" },
  { name: "딩동핑", season: "5기", collection: "스타 티니핑", tier: "normal", description: "보냄의 감정을 담당하는 스타 티니핑. 부지런하고 책임감 강한 우주별 마을의 배달부로, 배달받은 이의 기쁨으로 만들어진 별을 모아 로켓 연료로 충전한다.", image: "assets/딩동핑.webp" },
  { name: "나그네핑", season: "5기", collection: "스타 티니핑", tier: "normal", description: "낭만의 감정을 담당하는 스타 티니핑. 유유자적하고 느긋해 보이지만 실제로는 우울하고 체념적이며, 종이배를 통해 안 좋은 기억을 흘려보내게 돕는다.", image: "assets/나그네핑.webp" },
  { name: "고고핑", season: "5기", collection: "스타 티니핑", tier: "normal", description: "활달함의 감정을 담당하는 스타 티니핑. 걱정이 없고 긍정적이며 친구를 잘 챙기는 성격으로, 롤러스케이트로 속도를 조절하는 마법을 사용한다.", image: "assets/고고핑.webp" },
  { name: "뿌쵸핑", season: "5기", collection: "스타 티니핑", tier: "normal", description: "전시의 감정을 담당하는 스타 티니핑. 예쁘고 귀여운 것을 좋아하는 여성스럽지만 제멋대로인 성격으로, 마음에 드는 것을 마법의 스티커로 변환해 스티커북에 모은다.", image: "assets/뿌쵸핑.webp" },
  { name: "고마핑", season: "5기", collection: "스타 티니핑", tier: "normal", description: "튼튼함의 감정을 담당하는 스타 티니핑. 온화하고 상냥하지만 엄청난 괴력을 제어하지 못해 의도치 않게 주변에 피해를 주며, 힘 조절을 배워가는 성장형 캐릭터이다.", image: "assets/고마핑.webp" },
  { name: "아롱핑", season: "5기", collection: "스타 티니핑", tier: "normal", description: "어울림의 감정을 담당하는 스타 티니핑(언니). 차분하고 여성스러우며 여동생을 잘 챙기는 다정한 성격으로, 큰북으로 대상의 크기를 확대하는 마법을 사용한다.", image: "assets/아롱핑.webp" },
  { name: "다롱핑", season: "5기", collection: "스타 티니핑", tier: "normal", description: "어울림의 감정을 담당하는 스타 티니핑(동생). 활달하고 털털하지만 언니 앞에서는 어리광을 피우는 사랑스러운 성격으로, 작은북으로 대상의 크기를 축소하는 마법을 사용한다.", image: "assets/다롱핑.webp" },
  { name: "뽀송핑", season: "5기", collection: "스타 티니핑", tier: "normal", description: "뽀송함의 감정을 담당하는 스타 티니핑. 다정하고 푸근하지만 말을 잘 못 알아듣는 답답한 면이 있으며, 축축한 것을 극도로 혐오하고 3마리의 뽀송양을 데리고 다닌다.", image: "assets/뽀송핑.webp" },
  { name: "유리핑", season: "5기", collection: "스타 티니핑", tier: "normal", description: "투명함의 감정을 담당하는 스타 티니핑. 겁 많고 소심한 성격으로 작은 자극에도 쉽게 놀라 투명해져 숨어버리며, 마법으로 대상을 투명하게 만드는 능력이 있다.", image: "assets/유리핑.webp" },
  { name: "함께핑", season: "5기", collection: "스타 티니핑", tier: "normal", description: "협동심의 감정을 담당하는 스타 티니핑. 초면에도 금방 친해지는 뛰어난 친화력을 지녔으며, 마법 핸드 롤러로 주변 모두를 강제로 협력하게 만드는 외향적 성격이다.", image: "assets/함께핑.webp" },
  { name: "댄스핑", season: "5기", collection: "스타 티니핑", tier: "normal", description: "경쾌함의 감정을 담당하는 스타 티니핑. 춤 실력에 강한 자부심을 가진 활발한 성격으로, 리코더로 대상을 신나게 춤추게 만들며 슬픔도 춤으로 털어낼 수 있다고 믿는다.", image: "assets/댄스핑.webp" },
  { name: "여우핑", season: "5기", collection: "스타 티니핑", tier: "normal", description: "놀이의 감정을 담당하는 스타 티니핑. 장난치기를 좋아하는 영리하고 욕심 많은 성격으로, 마법의 모래시계로 자신과 타인의 모습을 여러 개로 복제할 수 있다.", image: "assets/여우핑.webp" },
  { name: "루루핑", season: "5기", collection: "스타 티니핑", tier: "normal", description: "재능(노래)의 감정을 담당하는 스타 티니핑. 사랑스럽고 감수성이 풍부한 싱어송라이터로, 진심을 담은 노래로 사람들에게 감동을 전달하는 것을 가장 소중히 여긴다.", image: "assets/루루핑.webp" },
  { name: "몰래핑", season: "5기", collection: "스타 티니핑", tier: "normal", description: "빼앗음의 감정을 담당하는 스타 티니핑. 정의롭고 단호하지만 엉뚱한 면도 있는 우주별 마을의 괴도로, 예고장을 보내고 나쁜 마음을 가진 이의 악의를 훔쳐간다.", image: "assets/몰래핑.webp" },
  { name: "뽀뽀핑", season: "5기", collection: "스타 티니핑", tier: "normal", description: "순정의 감정을 담당하는 스타 티니핑. 순진무구하고 해맑은 아기 티니핑으로 '뽀뽀'라고 옹알이하며, 뽀뽀를 날려 상대의 마음을 순하고 풀어지게 만드는 마법을 쓴다.", image: "assets/뽀뽀핑.webp" },

  // ===== 프린세스 티니핑 6기 =====
  { name: "뽀득핑", season: "6기", collection: "프린세스 티니핑", tier: "normal", description: "개운함의 감정을 담당하는 프린세스 티니핑. 조금이라도 더러우면 참지 못하는 결벽증적 성격으로, 마법의 샤워기 거품으로 주변을 강제로 깨끗이 만들어버린다.", image: "assets/뽀득핑.webp" },
  { name: "차밍핑", season: "6기", collection: "프린세스 티니핑", tier: "normal", description: "매력의 감정을 담당하는 프린세스 티니핑. 언제나 당당하고 자신의 감각을 신뢰하지만, 매력의 기준이 독특해 대머리나 비정상적으로 긴 손톱도 아름답다고 여긴다.", image: "assets/차밍핑.webp" },
  { name: "나비핑", season: "6기", collection: "프린세스 티니핑", tier: "normal", description: "가벼움의 감정을 담당하는 프린세스 티니핑. 이해심 많고 단순한 순진한 성격으로, 마법의 날개옷으로 다양한 대상에게 날개를 달아주어 날아오르게 만든다.", image: "assets/나비핑.webp" },
  { name: "실크핑", season: "6기", collection: "프린세스 티니핑", tier: "normal", description: "모험심의 감정을 담당하는 프린세스 티니핑. 겉으로는 얌전해 보이지만 강한 모험심과 보물에 대한 욕심을 지닌 로맨틱한 모험가 성격이다.", image: "assets/실크핑.webp" },
  { name: "스노우핑", season: "6기", collection: "프린세스 티니핑", tier: "normal", description: "얼림의 감정을 담당하는 프린세스 티니핑. 활동적이고 자신의 의견이 뚜렷하며 하고 싶은 것은 꼭 해야 직성이 풀리는 고집스러운 성격으로, 마법의 스키로 눈보라를 일으킨다.", image: "assets/스노우핑.webp" },
  { name: "이슬핑", season: "6기", collection: "프린세스 티니핑", tier: "normal", description: "청순함의 감정을 담당하는 프린세스 티니핑. 꽃을 아끼고 이타적인 순수한 마음씨로, 마법의 꽃에 맺힌 이슬로 기운이 빠진 대상의 에너지를 충전해준다.", image: "assets/이슬핑.webp" },
  { name: "쿨쿨핑", season: "6기", collection: "프린세스 티니핑", tier: "normal", description: "숙면의 감정을 담당하는 프린세스 티니핑. 느긋하고 여유로운 야행성 성격으로 잠을 매우 중시하며, 코를 골 때 주변 모두를 잠들게 만드는 강력한 마법을 사용한다.", image: "assets/쿨쿨핑.webp" },
  { name: "슈슈핑", season: "6기", collection: "프린세스 티니핑", tier: "normal", description: "진심의 감정을 담당하는 프린세스 티니핑. 신데렐라를 모티브로 한 책임감 있는 캐릭터로, 유리구두를 던져 대상의 시간을 이전으로 되돌리는 타임루프 능력을 보유한다.", image: "assets/슈슈핑.webp" },
  { name: "롱롱핑", season: "6기", collection: "프린세스 티니핑", tier: "normal", description: "자람의 감정을 담당하는 프린세스 티니핑. 라푼젤을 모티브로 한 우아하고 세련된 성격으로, 마법의 빗으로 대상의 머리카락을 길게 자라나게 만드는 능력이 있다.", image: "assets/롱롱핑.webp" },
  { name: "큐핑", season: "6기", collection: "프린세스 티니핑", tier: "normal", description: "호감의 감정을 담당하는 프린세스 티니핑. 큐피드 신화에서 영감을 받은 캐릭터로, 마법의 활과 화살을 사용해 싫어하는 마음을 없애고 호의적인 마음을 유도한다.", image: "assets/큐핑.webp" },
  { name: "야옹핑", season: "6기", collection: "프린세스 티니핑", tier: "normal", description: "도도함의 감정을 담당하는 프린세스 티니핑. 고양이를 모티브로 한 도도하고 앙칼진 성격으로 툭 하면 발톱을 세우며, 실뭉치를 사용해 무엇이든 낚는 능력이 있다.", image: "assets/야옹핑.webp" },

  // ===== 프린스 티니핑 6기 =====
  { name: "샤를핑", season: "6기", collection: "프린스 티니핑", tier: "normal", description: "명예의 감정을 담당하는 프린스 티니핑. 기사도적이면서도 허당끼 있는 로맨스 나라 출신으로, 하오체를 사용하고 마법의 검으로 강력한 칼바람을 일으킨다.", image: "assets/샤를핑.webp" },
  { name: "트롯핑", season: "6기", collection: "프린스 티니핑", tier: "normal", description: "흥겨움의 감정을 담당하는 프린스 티니핑. 한국 트로트 가수를 모티브로 한 독특한 캐릭터로, 황금 마이크와 코러스핑 소환 마법으로 개인 테마송을 보유한 유일한 남성 티니핑이다.", image: "assets/트롯핑.webp" },
  { name: "깨굴핑", season: "6기", collection: "프린스 티니핑", tier: "normal", description: "능청의 감정을 담당하는 프린스 티니핑. 표면상 감정과 실제 감정이 다른 능청스러운 매력을 지녔으며, 마법으로 주변 대상을 개구리처럼 울게 만드는 능력이 있다.", image: "assets/깨굴핑.webp" },
  { name: "젠틀핑", season: "6기", collection: "프린스 티니핑", tier: "normal", description: "정중함의 감정을 담당하는 프린스 티니핑. 매너의 나라 출신의 신사적이고 정중한 성품을 지녔으며, 마법의 우산으로 주변 대상을 젠틀하게 만들어주는 능력이 있다.", image: "assets/젠틀핑.webp" },

  // ===== 빌런 티니핑 =====
  { name: "트러핑", season: "3기", collection: "빌런 티니핑", tier: "villain", description: "배신감과 절망의 감정으로 흑화한 빌런 티니핑. 리암 왕자에게 버려졌다고 오해해 타락했으며, 다른 티니핑을 세뇌하고 인간-티니핑의 우정을 부정하다가 진실을 알고 갱생한다.", image: "assets/트러핑.webp" },
  { name: "다해핑", season: "2기", collection: "빌런 티니핑", tier: "villain", description: "헌신의 감정을 담당하는 빌런 티니핑. 제니를 위해 무엇이든 하는 맹목적인 성격으로, 하츄핑에 대한 강한 열등감을 지녔으나 3기 후반부에 자신의 잘못을 깨닫고 갱생한다.", image: "assets/다해핑.webp" },
  { name: "가면핑", season: "2기", collection: "빌런 티니핑", tier: "villain", description: "담당 감정이 불명인 빌런 티니핑. 마법의 열쇠와 최면 피리로 직접 싸우기보다 심리 조종과 속임수를 선호하는 지능형 악역으로, 2기 메인 빌런이다.", image: "assets/가면핑.webp" },
  { name: "악동핑", season: "1기", collection: "빌런 티니핑", tier: "villain", description: "담당 감정이 불분명한 빌런 티니핑. 장난치기와 골탕 먹이기를 즐기는 말썽꾸러기로, 번개 뿅망치 마법을 사용하며 간섭과 명령 받는 것을 극도로 싫어한다.", image: "assets/악동핑.webp" },
];
